make vite test run in frontend folder instead of root folder

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,7 +23,7 @@ jobs:
         run: npm run build --prefix frontend
 
       - name: Test frontend build output exists
-        run: test -d dist && echo "Build successful" || echo "Build failed"
+        run: test -d frontend/dist && echo "Build successful" || echo "Build failed"
 
       - name: Install strapi dependencies
         run: npm ci --prefix strapi
