Feature/joined repos backend frontend (#20)
* Add strapi and modify actions

* remove git folder from strapi project

* fix build errors

* add strapi build to build action

* add plugins submodule

* Add missing changes

* add guben cockpit plugins install to build

* make vite test run in frontend folder instead of root folder

* add prebuild script to strapi build

* remove plugins install because prebuild script will handle that

* add recursive submodules to checkout

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,17 +10,28 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          submodules: recursive
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
           node-version: '20'
 
-      - name: Install dependencies
-        run: npm ci
+      - name: Install frontend dependencies
+        run: npm ci --prefix frontend
 
       - name: Build Vite app
-        run: npm run build
+        run: npm run build --prefix frontend
 
-      - name: Test build output exists
-        run: test -d dist && echo "Build successful" || echo "Build failed"
+      - name: Test frontend build output exists
+        run: test -d frontend/dist && echo "Build successful" || echo "Build failed"
+
+      - name: Install strapi dependencies
+        run: npm ci --prefix strapi
+
+      - name: Run prebuild Strapi
+        run: npm run prebuild --prefix strapi
+
+      - name: Build Strapi
+        run: npm run build --prefix strapi
